# WhatATheme
markdown: kramdown

# URL of the Site
url: https://amsterdamparentproject.nl
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Amsterdam Parent Project
# Description of the Site
description: Peer-to-peer support for new parents, (em)powered by professionals
# URL of Image of the Site
site-image: /assets/images/web-share.png
# Keywords of the Site
site-keywords: Parents, Amsterdam
# URL for the Image of custom Favicons
favicon-url:  assets/images/favicon.ico
logo-url: assets/images/logo.png
logo-text-url: assets/images/logo-text.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: amsterdamparentproject@gmail.com
instagram-username: amsterdamparentproject
instagram-link: https://www.instagram.com/amsterdamparentproject/
roadmap-link: https://trello.com/b/yUO7aIps/roadmap-amsterdam-parent-project-app

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Authors
alex-name: Alex Siega
alex-title: Founder, Amsterdam Parent Project
alex-image: /assets/images/about/alex-square.jpg
alex-bio: Founder of APP and expat mama in Amsterdam West
alex-linkedin: https://www.linkedin.com/in/alexandrasiega/
alex-instagram: https://www.instagram.com/amsterdamparentproject/

miriam-name: Dr. Irena Domachowska
miriam-title: Co-Founder, Amsterdam Parent Project
miriam-image: /assets/images/about/miriam-square.png
miriam-bio: 
miriam-linkedin: https://www.linkedin.com/in/irena-domachowska-709b3a54/
miriam-instagram: 

heather-name: Heather Berry
heather-title: Consultant, Fourth Trimester Program and Ask APP contributor
heather-image: /assets/images/about/heather-square.jpeg
heather-bio: 
heather-linkedin: https://www.linkedin.com/in/heather-berry 
heather-instagram: https://www.instagram.com/the4thtrimestersupport/
heather-website: https://berrycareandcoaching.com

# Program images
newlsetter-banner: /assets/images/just-a-phase-banner.png

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "newsletter/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
